name: "TruffleHog PR Scan"
description: "Scan changed files in a PR for secrets"

runs:
  using: "composite"
  steps:
    - name: Install trufflehog
      run: |
        set -euo pipefail

        # Get latest release tag from GitHub API (e.g. v3.91.2 -> 3.91.2)
        VERSION=$(curl -s https://api.github.com/repos/trufflesecurity/trufflehog/releases/latest \
          | grep -Po '"tag_name":\s*"v\K[0-9.]+' )

        if [ -z "${VERSION:-}" ]; then
          echo "Could not determine latest TruffleHog version" >&2
          exit 1
        fi

        echo "Installing TruffleHog ${VERSION}"

        curl -sSL -o trufflehog.tar.gz \
          "https://github.com/trufflesecurity/trufflehog/releases/latest/download/trufflehog_${VERSION}_linux_amd64.tar.gz"

        tar -xzf trufflehog.tar.gz
        install trufflehog /usr/local/bin/trufflehog

        trufflehog --version

    - name: Determine changed files
      id: diff
      run: |
        set -euo pipefail

        if ! command -v jq >/dev/null 2>&1; then
          echo "jq not found, installing..."
          apt-get update -y
          apt-get install -y jq
        fi

        echo "Event file: $GITHUB_EVENT_PATH"

        BASE_SHA=$(jq -r '.pull_request.base.sha' "$GITHUB_EVENT_PATH")
        HEAD_SHA=$(jq -r '.pull_request.head.sha' "$GITHUB_EVENT_PATH")

        echo "Base SHA (PR target): $BASE_SHA"
        echo "Head SHA (PR branch): $HEAD_SHA"

        git fetch --no-tags --prune origin "$BASE_SHA" "$HEAD_SHA"
        git diff --name-only --diff-filter=AM "$BASE_SHA" "$HEAD_SHA" > changed_files.txt

        if [ ! -s changed_files.txt ]; then
          echo "No added or modified files in this PR."
          echo "has_changes=false" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "Files changed in this PR:"
        cat changed_files.txt

        # Build include-paths file for TruffleHog:
        # one regex per line, matching full paths; escape regex metacharacters
        awk '{
          gsub(/[][().^$*+?{}|\\]/, "\\\\&");
          print "^" $0 "$"
        }' changed_files.txt > include_paths.txt

        echo "Generated include_paths.txt:"
        cat include_paths.txt

        echo "has_changes=true" >> "$GITHUB_OUTPUT"

    - name: Run trufflehog scan
      if: steps.diff.outputs.has_changes == 'true'
      run: |
        trufflehog filesystem . \
          --include-paths include_paths.txt \
          --fail
